### ISSUE TITLE
Is there a way to backup all existing databases in one go? Else can multiple database backups (manually defined) be saved to a single file?

### ISSUE THREAD

**Issue by paripooranan** [lihaibh/mongodb-snapshot#16]

**Comment by lihaibh** [comment]
There is no such a feature currently, you can only use the same source and transfer it to multiple targets, for example, copy database to multiple databases or database + file, etc...

in your case you want multiple sources to transfer to a single target.
The reason why i didnt do it is because i wanted to preserve the backup in a known format.

We can add a feature though to ease the use of the library to create multiple files for each database.

**Comment by paripooranan** [comment]
Thanks!
